// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Các component client dùng thẳng bên dưới — KHÔNG cần "use client" ở file này
import RouteLoader from "@/components/common/route-loader";
import { AuthProvider } from "@/contexts/AuthContext";
import { Suspense } from "react";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AIDS-LMS",
  description: "Generated by create next app",
  icons: {
    // provide explicit icon objects so Next emits proper <link rel="icon"> tags
    icon: [
      { url: "/logo-aids-lms.svg", type: "image/png" },
    ],
    shortcut: "/logo-aids-lms.svg",
    apple: "/logo-aids-lms.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Client comps dùng trực tiếp trong Server layout */}
        <Suspense fallback={null}>
          <RouteLoader />
        </Suspense>

        <AuthProvider>
          {children}
        </AuthProvider>

        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
